config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
  end

  root 'queries#query'

  get 'query',      to: 'queries#query'
  get 'search_cep', to: 'queries#search_cep', as: :search_cep
end

app/models/query.rb
class Query < ActiveRecord::Base
  validates :cep, :status, :response, presence: true

  scope :successful, -> { where(status: true)}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email    = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  def query
    @query_form = QueryForm.new
    @queries    = Query.successful.order('id DESC')
  end

  def search_cep
    @query_form = QueryForm.new(query_params)
    if @query_form.valid?
      @result = QueryCepService.new(@query_form.cep).find
    end
  end

  private
  def query_params
    params.require(:query_form).permit(:cep)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      set_flash_message(:error, :failure, :kind => "Facebook", reason: 'we had problems with your facebook account') if is_navigational_format?
      redirect_to new_user_session_path
    end
  end

  def failure
    redirect_to new_user_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
  def table_line
    string = <<-HTML
      <tr>
        <td>#{@result.cep}</td>
        <td>#{@result.tipo_de_logradouro} #{@result.logradouro}</td>
        <td>#{@result.bairro}</td>
        <td>#{@result.cidade}</td>
        <td>#{@result.estado}</td>
      </tr>
    HTML
    string.html_safe
  end

  def error_flash_line
    string = <<-HTML
      <div class='alert alert-danger' role='alert'>
        <button type='button' class='close' data-dismiss='alert'>×</button>
        #{@result.dig(:error)}
      </div>
    HTML
    string.html_safe
  end

  def field_error
    content_tag(:span, @query_form.errors.messages.dig(:cep).first, class: 'text-error')
  end
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : 'Address By Cep - Gallerr'
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        .navbar-header.pull-left
          = link_to(t('login.title'), root_path, class: 'navbar-brand')
        - if current_user.present?
          .navbar-header.pull-right
            %p.navbar-text
              %b=current_user.email
              = link_to 'Logout', sign_out_path, method: :delete
    .container
      .row
        .col-lg-12.input-ajax-flashes
          = bootstrap_flash
          = yield

app/views/queries/_address.html.haml
.col-lg-5
  = result.cep
  %br
  = "#{result.tipo_de_logradouro} #{result.logradouro}, #{result.bairro}"
  %br
  = "#{result.cidade}, #{result.estado}"

app/views/queries/_query_history.html.haml
.query-history.collapse
  .row
    .col-lg-10
      %h4= t('query_history.title')
    .col-sm-10
      %table.table{id: 'address-container'}
        %thead
          %tr
            %th= t('query_history.cep')
            %th= t('query_history.address')
            %th= t('query_history.neighborhood')
            %th= t('query_history.city')
            %th= t('query_history.state')
        %tbody
          - collection.each do |query|
            - result = ObjectifiedResponseService.new(query.response).object
            %tr
              %td=result.cep
              %td="#{result.tipo_de_logradouro} #{result.logradouro}"
              %td=result.bairro
              %td=result.cidade
              %td=result.estado

app/views/queries/_result.html.haml
.row
  .col-lg-10
    %h4= t('query.found_zipcode')
  = render 'address', result: @result

app/views/queries/query.html.haml
.page-header
  %h2= t('query.title')

= form_for @query_form, url: search_cep_path, remote: true, method: :get, html: { class: "form form-horizontal query" } do |f|
  .form-group
    = f.label :cep, t('query.zipcode'), class: 'control-label col-lg-2'
    .col-lg-3
      = f.text_field :cep, class: 'form-control'
    = f.error_span(:cep)

  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit t('query.find'), class: 'btn btn-primary'
      = link_to t('query.show_history'), '#', id: 'show-history', :class => 'btn btn-default'
      = link_to t('query.cancel'), root_path, :class => 'btn btn-default'

.query-result

= render 'query_history', collection: @queries

app/views/queries/search_cep.js.haml
- if @query_form.errors.blank? 
  - unless @result.is_a?(Hash)
    $('.query-result').append("#{escape_javascript render 'result'}");
    $('#address-container tbody').prepend("#{escape_javascript table_line}");  
  - else
    $('.input-ajax-flashes').prepend("#{escape_javascript error_flash_line}");
- else
  $('#query_form_cep').parent().append("#{escape_javascript field_error}");
  $('.form-group').addClass('has-error');